spring:
  datasource:
    url: jdbc:mysql://localhost:23306/vpot_srv?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&generateSimpleParameterMetadata=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

camunda:
  bpm:
    # 配置账户密码来访问Camunda自带的管理界面
    admin-user:
      id: admin
      password: admin
      first-name: admin
    filter:
      create: All tasks
    #禁止自动部署resources下面的bpmn文件
    auto-deployment-enabled: false
    #指定数据库类型
    database:
      type: mysql
    #禁止index跳转到Camunda自带的管理界面，默认true
#    webapp:
#      index-redirect-enabled: false
    generic-properties:
      properties:
        javaSerializationFormatEnabled: true
        deserializationTypeValidationEnabled: true